apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rapid-mandrill-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rapid-mandrill-python 
  name: rapid-mandrill-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rapid-mandrill-python 
