apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rapid-mandrill-python-gitops
  description: This is GitOps manifest for rapid-mandrill-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rapid-mandrill-python
    janus-idp.io/tekton: rapid-mandrill-python 
    backstage.io/kubernetes-id: rapid-mandrill-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rapid-mandrill-python
